spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: employee
    password: employee
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
#